# Generated by Django 5.2.12 on 2026-03-07 16:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_last_donation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['criteria_value']},
        ),
        migrations.AlterModelOptions(
            name='charity',
            options={'ordering': ['name'], 'verbose_name_plural': 'Charities'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='impactupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='needrequest',
            options={'ordering': ['-urgency', 'deadline']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-earned_at']},
        ),
        migrations.AlterField(
            model_name='badge',
            name='criteria_type',
            field=models.CharField(choices=[('donation_count', 'Donation Count'), ('coin_threshold', 'Coin Threshold'), ('streak_days', 'Streak Days')], max_length=100),
        ),
        migrations.AlterField(
            model_name='badge',
            name='criteria_value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='charity',
            name='contact',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='charity',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='charity',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='charity',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='qty',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='impactupdate',
            name='caption',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='needrequest',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='needrequest',
            name='qty_needed',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='needrequest',
            name='qty_pledged',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='needrequest',
            name='urgency',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='challenge_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='team',
            name='challenge_goal',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='give_coins',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='streak_days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='api.badge'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='needrequest',
            constraint=models.CheckConstraint(condition=models.Q(('qty_pledged__lte', models.F('qty_needed'))), name='qty_pledged_lte_qty_needed'),
        ),
        migrations.AddConstraint(
            model_name='needrequest',
            constraint=models.CheckConstraint(condition=models.Q(('qty_pledged__gte', 0)), name='qty_pledged_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='userbadge',
            constraint=models.UniqueConstraint(fields=('user', 'badge'), name='unique_user_badge'),
        ),
    ]
