# Generated by Django 5.2.12 on 2026-03-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_badge_options_alter_charity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needrequest',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='challenge_deadline',
            field=models.DateTimeField(),
        ),
    ]
