# Generated by Django 5.2.12 on 2026-03-07 17:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_needrequest_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needrequest',
            name='deadline',
            field=models.DateTimeField(default=api.models.one_week_hence),
        ),
        migrations.AlterField(
            model_name='team',
            name='challenge_deadline',
            field=models.DateTimeField(default=api.models.one_week_hence),
        ),
    ]
